services:
  web:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "testing"
    ports:
      - 3306:3306
